name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build, Push and Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: latam-flight-model-prod
      PROJECT_ID: delaylatammodel
      SERVICE_NAME: latam-flight-service-prod

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image=gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated
